sudo: false
language: node_js

node_js:
  - "10.15"

dist: trusty
branches:
  only:
    - ch-add-tests-164252950
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install 
  - npm install --save-dev babel-plugin-transform-es2015-modules-commonjs
  - npm i jest puppeteer faker --save-dev
script:
  - npm start &
  - npm test
after_success:
  - npm run coveralls
services:
  - http-server